const OPENAI_API_KEY =
  process.env.OPENAI_API_KEY || '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'
const OPENAI_ORGANIZATION = process.env.OPENAI_ORGANIZATION

export { OPENAI_API_KEY, OPENAI_ORGANIZATION }
